### ISSUE TITLE
question about inpainting

### ISSUE THREAD

**Issue by liangyuxin42** [robopen/roboagent#10]
Thank you for your excellent work, I am very inspired!
I have a question about the data augmentation, what tools/models did you use for inpainting and how was the corresponding prompt chosen?
Looking forward to your reply, thanks!

**Comment by homangab** [comment]
Thanks for the question, and glad you liked our work. 

For obtaining masks of random objects in the scenes, we used SegmentAnything (SAM) from Meta. Any pre-trained text2image generative models could be used for the inpainting given masks from SAM and a prompt . The prompts were simply a list of several different everyday objects in scenes like, "fruits on a table," "utensils next to the counter" We didn't try to automate/scale this process of choosing prompts (since the text2image models are already stochastic- and given different masks obtained from SAM, with the same language prompt, the inpainted images are all very different)

We will put out a script for doing this inpainting, in the repo (sorry for the delay in this)

**Comment by liangyuxin42** [comment]
Got it, thanks for the reply, looking forward to your updates!
